# Dockerfile.db - Imagen personalizada de PostgreSQL con datos incluidos
FROM postgres:15-alpine

# Copiar el backup al directorio de inicialización
ENV POSTGRES_DB=proshooter_db_prod
ENV POSTGRES_USER=admin
ENV POSTGRES_PASSWORD=quTBg7FtWz
# PostgreSQL ejecuta automáticamente cualquier .sql que encuentre aquí
COPY db_backups/backup.sql /docker-entrypoint-initdb.d/01-restore-data.sql
COPY db_backups/fix-permission.sql /docker-entrypoint-initdb.d/02-fix-permissions.sql

# Etiquetas para documentar la imagen
LABEL description="PostgreSQL con datos de ProShooter API incluidos"
LABEL version="1.0"
