FROM python:3.12-slim

# SET WORKING DIRECTORY
WORKDIR /app

# SET ENVIRONMENT VARIABLEs
ENV PIP_DISABLE_PIP_VERSION_CHECK=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app


# Install system dependencies
RUN apt-get update \
    && apt-get install -y --no-install-recommends gcc libpq-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# INSTALL DEPENDENCIES
COPY requirements.txt .
# Install basic packages first
RUN pip install --no-cache-dir --upgrade pip setuptools wheel
# Now install the requirements with verbose output to see any errors clearly
RUN pip install --no-cache-dir -v -r requirements.txt

# Copy project
COPY . .

# Create a non-root user and switch to it
RUN adduser --disabled-password --gecos '' appuser
RUN chown -R appuser:appuser /app
USER appuser

EXPOSE 8000

# CMD ["uvicorn", "src.main:app","--reload", "--host", "0.0.0.0", "--port", "8000"]
