"""Entidad de evaluacion

Revision ID: 00f6c6e6ceb4
Revises: 217eb8bae840
Create Date: 2025-04-13 16:23:21.686916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '00f6c6e6ceb4'
down_revision: Union[str, None] = '217eb8bae840'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practice_evaluations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('evaluator_id', sa.UUID(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('classification', postgresql.ENUM('EXPERTO', 'CONFIABLE', 'MEDIO', 'REGULAR', name='shooterlevelenum', create_type=False), nullable=False),
    sa.Column('strengths', sa.String(), nullable=True),
    sa.Column('weaknesses', sa.String(), nullable=True),
    sa.Column('recomendations', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['evaluator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['individual_practice_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('practice_evaluations')
    # ### end Alembic commands ###
