"""Corrigiendo el campo de first_name

Revision ID: 0d96449b99ce
Revises: 6bc67ddcfbae
Create Date: 2025-02-23 10:33:12.219799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d96449b99ce'
down_revision: Union[str, None] = '6bc67ddcfbae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_biometric_data', 'imc')
    op.add_column('user_personal_data', sa.Column('first_name', sa.String(), nullable=False))
    op.drop_column('user_personal_data', 'fist_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_personal_data', sa.Column('fist_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('user_personal_data', 'first_name')
    op.add_column('user_biometric_data', sa.Column('imc', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
