"""Cargando el modelo del club en alembic

Revision ID: 0ead4031dc1e
Revises: 5661c31cd00a
Create Date: 2025-03-03 19:30:58.017103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ead4031dc1e'
down_revision: Union[str, None] = '5661c31cd00a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
