"""Forzando la relacion 1 a 1 a nivel de base de datos

Revision ID: 169261811dba
Revises: 88e8d2ad7c77
Create Date: 2025-02-24 22:27:15.334784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '169261811dba'
down_revision: Union[str, None] = '88e8d2ad7c77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_biometric_data', 'id')
    op.drop_column('user_medical_data', 'id')
    op.drop_column('user_personal_data', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_personal_data', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('user_medical_data', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('user_biometric_data', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
