"""Agregando las relaciones de analisis de disparo y recomendaciones

Revision ID: 1916b9cfc4fd
Revises: 3ff5d0788178
Create Date: 2025-04-13 17:44:28.431180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1916b9cfc4fd'
down_revision: Union[str, None] = '3ff5d0788178'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('target_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['practice_exercises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('target_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('target_image_id', sa.UUID(), nullable=False),
    sa.Column('analysis_timestamp', sa.DateTime(), nullable=True),
    sa.Column('total_impacts_detected', sa.Integer(), nullable=True),
    sa.Column('zone_distribution', sa.JSON(), nullable=True),
    sa.Column('impact_coordinates', sa.JSON(), nullable=True),
    sa.Column('analysis_confidence', sa.Float(), nullable=True),
    sa.Column('analysis_method', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['target_image_id'], ['target_images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shooting_recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('primary_issue_zone', sa.String(), nullable=False),
    sa.Column('primary_issue_zone_description', sa.String(), nullable=False),
    sa.Column('secondary_issue_zone', sa.String(), nullable=True),
    sa.Column('secondary_issue_zone_description', sa.String(), nullable=True),
    sa.Column('recommended_exercises', sa.JSON(), nullable=True),
    sa.Column('recommendation_description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['target_analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shooting_recommendations')
    op.drop_table('target_analyses')
    op.drop_table('target_images')
    # ### end Alembic commands ###
