"""Cambiando el id de shooter en usuario

Revision ID: 19751d92b5c2
Revises: 104c68497367
Create Date: 2025-02-24 22:53:53.884183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19751d92b5c2'
down_revision: Union[str, None] = '104c68497367'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
