"""Agregando la relacion entre tipo de practica y ejercicio 2

Revision ID: 1a8cd89c06b9
Revises: c42a3753e4c6
Create Date: 2025-04-13 14:50:23.079645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a8cd89c06b9'
down_revision: Union[str, None] = 'c42a3753e4c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practice_exercises',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('exercise_type_id', sa.UUID(), nullable=False),
    sa.Column('distance', sa.String(), nullable=False),
    sa.Column('firing_cadence', sa.String(), nullable=True),
    sa.Column('time_limit', sa.String(), nullable=True),
    sa.Column('ammunition_allocated', sa.Integer(), nullable=True),
    sa.Column('ammunition_used', sa.Integer(), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=True),
    sa.Column('accuracy_percentage', sa.Float(), nullable=True),
    sa.Column('reaction_time', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['exercise_type_id'], ['exercise_types.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['individual_practice_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('practice_exercises')
    # ### end Alembic commands ###
