"""Agregando la evaluacion en el modelo de sesion practica

Revision ID: 1b848b09de36
Revises: 1916b9cfc4fd
Create Date: 2025-04-13 18:36:03.961401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b848b09de36'
down_revision: Union[str, None] = '1916b9cfc4fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
