"""add target_image_id to practice_exercise

Revision ID: 1eec9bcd4a3c
Revises: 7687e4b16c5a
Create Date: 2025-07-17 20:00:10.633666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eec9bcd4a3c'
down_revision: Union[str, None] = '7687e4b16c5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practice_exercises', sa.Column('target_image_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'practice_exercises', 'target_images', ['target_image_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'practice_exercises', type_='foreignkey')
    op.drop_column('practice_exercises', 'target_image_id')
    # ### end Alembic commands ###
