"""Cargando las demas relaciones en la tabla de ejercicio practico

Revision ID: 217eb8bae840
Revises: 748c76d20c82
Create Date: 2025-04-13 15:02:35.288782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '217eb8bae840'
down_revision: Union[str, None] = '748c76d20c82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practice_exercises', sa.Column('weapon_id', sa.UUID(), nullable=False))
    op.add_column('practice_exercises', sa.Column('ammunition_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'practice_exercises', 'ammunition', ['ammunition_id'], ['id'])
    op.create_foreign_key(None, 'practice_exercises', 'weapons', ['weapon_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'practice_exercises', type_='foreignkey')
    op.drop_constraint(None, 'practice_exercises', type_='foreignkey')
    op.drop_column('practice_exercises', 'ammunition_id')
    op.drop_column('practice_exercises', 'weapon_id')
    # ### end Alembic commands ###
