"""agregando el tipo a los ejercicios

Revision ID: 34dc0c708091
Revises: b2c52305e39d
Create Date: 2025-07-24 12:46:53.232988

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "34dc0c708091"
down_revision: Union[str, None] = "b2c52305e39d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("exercise_types", sa.Column("type", sa.String(), nullable=True))
    op.execute("UPDATE exercise_types SET type = 'precision' WHERE type IS NULL")
    op.alter_column("exercise_types", "type", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("exercise_types", "type")
    # ### end Alembic commands ###
