"""Cambiando la relacion en el metodo

Revision ID: 36f3ff3da1c0
Revises: 439ac7ee24ce
Create Date: 2025-02-27 02:42:49.984737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36f3ff3da1c0'
down_revision: Union[str, None] = '439ac7ee24ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
