"""Actualizando los stats del tirador

Revision ID: 3e0099fbd3f7
Revises: f41229210d09
Create Date: 2025-05-03 21:27:12.419032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e0099fbd3f7'
down_revision: Union[str, None] = 'f41229210d09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shooter_stats', sa.Column('trend_accuracy', sa.Float(), nullable=True))
    op.add_column('shooter_stats', sa.Column('last_10_sessions_avg', sa.Float(), nullable=True))
    op.add_column('shooter_stats', sa.Column('precision_exercise_accuracy', sa.Float(), nullable=True))
    op.add_column('shooter_stats', sa.Column('reaction_exercise_accuracy', sa.Float(), nullable=True))
    op.add_column('shooter_stats', sa.Column('movement_exercise_accuracy', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shooter_stats', 'movement_exercise_accuracy')
    op.drop_column('shooter_stats', 'reaction_exercise_accuracy')
    op.drop_column('shooter_stats', 'precision_exercise_accuracy')
    op.drop_column('shooter_stats', 'last_10_sessions_avg')
    op.drop_column('shooter_stats', 'trend_accuracy')
    # ### end Alembic commands ###
