"""Modelo para datos de rendimiento del tirador

Revision ID: 3e643d718eef
Revises: c6a0be452f64
Create Date: 2025-04-10 00:41:31.510313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e643d718eef'
down_revision: Union[str, None] = 'c6a0be452f64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
