"""Agregando las relaciones de analisis de disparo y recomendaciones

Revision ID: 3ff5d0788178
Revises: 00f6c6e6ceb4
Create Date: 2025-04-13 17:17:25.758728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ff5d0788178'
down_revision: Union[str, None] = '00f6c6e6ceb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
