"""Agregando los stats del tirador

Revision ID: 4888a1eb7247
Revises: 36f3ff3da1c0
Create Date: 2025-02-28 19:08:55.329652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4888a1eb7247'
down_revision: Union[str, None] = '36f3ff3da1c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shooter_stats',
    sa.Column('shooter_id', sa.UUID(), nullable=False),
    sa.Column('total_shots', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Integer(), nullable=False),
    sa.Column('average_hit_factor', sa.Float(), nullable=False),
    sa.Column('effectiveness', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['shooter_id'], ['shooters.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('shooter_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shooter_stats')
    # ### end Alembic commands ###
