"""Modelo para datos de rendimiento del tirador cargando modelo

Revision ID: 49b43e5a1a75
Revises: 3e643d718eef
Create Date: 2025-04-10 00:43:38.419235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49b43e5a1a75'
down_revision: Union[str, None] = '3e643d718eef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shooter_performance_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shooter_id', sa.UUID(), nullable=False),
    sa.Column('metric_type', sa.String(), nullable=True),
    sa.Column('metric_value', sa.String(), nullable=True),
    sa.Column('context', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['shooter_id'], ['shooters.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shooter_performance_logs')
    # ### end Alembic commands ###
