"""Agregando el genero a la info personal del usuario

Revision ID: 4d91f1787c7f
Revises: 6f257d859a95
Create Date: 2025-06-15 03:45:01.765398

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4d91f1787c7f"
down_revision: Union[str, None] = "6f257d859a95"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('user_personal_data', sa.Column('genre', sa.String(), nullable=False, server_default="N/A"))
    # ### end Alembic commands ###
    op.add_column(
        "user_personal_data",
        sa.Column("genre", sa.String(), nullable=False, server_default="N/A"),
    )
    op.alter_column("user_personal_data", "genre", server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_personal_data", "genre")
    # ### end Alembic commands ###
