"""Nuevo campo en la sesion de practica para saber si le falta una evaluacion

Revision ID: 52363926f2d2
Revises: 3e0099fbd3f7
Create Date: 2025-05-03 21:41:48.402063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52363926f2d2'
down_revision: Union[str, None] = '3e0099fbd3f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('individual_practice_sessions', sa.Column('evaluation_pending', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('individual_practice_sessions', 'evaluation_pending')
    # ### end Alembic commands ###
