"""Cargando los modelos de arma, municion y blanco

Revision ID: 556521ce90f0
Revises: 27add196f9a7
Create Date: 2025-03-10 21:21:09.732301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '556521ce90f0'
down_revision: Union[str, None] = '27add196f9a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ammunition',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('caliber', sa.String(), nullable=False),
    sa.Column('ammo_type', sa.Enum('STANDARD', 'COMPETITION', 'PRACTICE', 'MATCH', 'HOLLOW_POINT', 'FULL_METAL_JACKET', 'SUBSONIC', 'OTHER', name='ammotype'), nullable=False),
    sa.Column('grain_weight', sa.Float(), nullable=True),
    sa.Column('velocity', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_per_round', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('targets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('target_type', sa.Enum('CONCENTRIC', 'IPSC', name='targettype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scoring_zones', sa.JSON(), nullable=True),
    sa.Column('dimensions', sa.String(), nullable=True),
    sa.Column('distance_recommended', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weapons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('serial_number', sa.String(), nullable=False),
    sa.Column('weapon_type', sa.Enum('PISTOL', 'RIFLE', 'REVOLVER', 'SHOTGUN', 'CARBINE', 'SMG', 'SNIPER_RIFLE', 'OTHER', name='weapontypeenum'), nullable=False),
    sa.Column('caliber', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_table('weapon_ammunition_compatibility',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('weapon_id', sa.UUID(), nullable=False),
    sa.Column('ammunition_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ammunition_id'], ['ammunition.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['weapon_id'], ['weapons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weapon_ammunition_compatibility')
    op.drop_table('weapons')
    op.drop_table('targets')
    op.drop_table('ammunition')
    # ### end Alembic commands ###
