"""Agregando el campo del club id al tirador

Revision ID: 5661c31cd00a
Revises: 1d91a0cc6717
Create Date: 2025-03-03 16:00:16.391395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5661c31cd00a'
down_revision: Union[str, None] = '1d91a0cc6717'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shooters', sa.Column('club_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'shooters', 'shooting_clubs', ['club_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shooters', type_='foreignkey')
    op.drop_column('shooters', 'club_id')
    # ### end Alembic commands ###
