"""Indexando el alias del usuario

Revision ID: 585e90d35362
Revises: 4d91f1787c7f
Create Date: 2025-06-15 04:08:30.764570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '585e90d35362'
down_revision: Union[str, None] = '4d91f1787c7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('shooters_nickname_key', 'shooters', type_='unique')
    op.create_index(op.f('ix_shooters_nickname'), 'shooters', ['nickname'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shooters_nickname'), table_name='shooters')
    op.create_unique_constraint('shooters_nickname_key', 'shooters', ['nickname'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
