"""Agregando los datos del seguro a los datos medicos del usuario

Revision ID: 626bce9c65fd
Revises: 73505fefdebb
Create Date: 2025-07-21 17:31:43.282609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '626bce9c65fd'
down_revision: Union[str, None] = '73505fefdebb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_medical_data', sa.Column('insurance_provider', sa.String(), nullable=True))
    op.add_column('user_medical_data', sa.Column('insurance_number', sa.String(), nullable=True))
    op.add_column('user_medical_data', sa.Column('insurance_expiry', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_medical_data', 'insurance_expiry')
    op.drop_column('user_medical_data', 'insurance_number')
    op.drop_column('user_medical_data', 'insurance_provider')
    # ### end Alembic commands ###
