"""indicador de sesion terminada

Revision ID: 677e4a438490
Revises: 626bce9c65fd
Create Date: 2025-07-21 19:47:17.149701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '677e4a438490'
down_revision: Union[str, None] = '626bce9c65fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('individual_practice_sessions', sa.Column('is_finished', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('individual_practice_sessions', 'is_finished')
    # ### end Alembic commands ###
