"""Agregando el apodo y la licencia al tirador

Revision ID: 6f257d859a95
Revises: 52363926f2d2
Create Date: 2025-05-25 00:19:04.011069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f257d859a95'
down_revision: Union[str, None] = '52363926f2d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shooters', sa.Column('nickname', sa.String(), nullable=True))
    op.add_column('shooters', sa.Column('license_file', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'shooters', ['nickname'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shooters', type_='unique')
    op.drop_column('shooters', 'license_file')
    op.drop_column('shooters', 'nickname')
    # ### end Alembic commands ###
