"""add_analysis_columns_to_target_analysis

Revision ID: 73505fefdebb
Revises: ec29d19c718b
Create Date: 2025-07-19 04:25:50.428226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73505fefdebb'
down_revision: Union[str, None] = 'ec29d19c718b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('target_analyses', sa.Column('fresh_impacts_inside', sa.Integer(), nullable=True))
    op.add_column('target_analyses', sa.Column('fresh_impacts_outside', sa.Integer(), nullable=True))
    op.drop_column('target_analyses', 'total_impacts_inside')
    op.drop_column('target_analyses', 'total_impacts_outside')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('target_analyses', sa.Column('total_impacts_outside', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('target_analyses', sa.Column('total_impacts_inside', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('target_analyses', 'fresh_impacts_outside')
    op.drop_column('target_analyses', 'fresh_impacts_inside')
    # ### end Alembic commands ###
