"""Cargando la relacion de blanco y ejercicio

Revision ID: 748c76d20c82
Revises: 1a8cd89c06b9
Create Date: 2025-04-13 14:56:26.259519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '748c76d20c82'
down_revision: Union[str, None] = '1a8cd89c06b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practice_exercises', sa.Column('target_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'practice_exercises', 'targets', ['target_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'practice_exercises', type_='foreignkey')
    op.drop_column('practice_exercises', 'target_id')
    # ### end Alembic commands ###
