"""Agregando fechas de creacion y edicion a los datos de los usuarios

Revision ID: 76658dd2c90e
Revises: 0d96449b99ce
Create Date: 2025-02-24 21:24:30.439469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76658dd2c90e'
down_revision: Union[str, None] = '0d96449b99ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_biometric_data', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('user_biometric_data', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_medical_data', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('user_medical_data', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_personal_data', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('user_personal_data', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_personal_data', 'updated_at')
    op.drop_column('user_personal_data', 'created_at')
    op.drop_column('user_medical_data', 'updated_at')
    op.drop_column('user_medical_data', 'created_at')
    op.drop_column('user_biometric_data', 'updated_at')
    op.drop_column('user_biometric_data', 'created_at')
    # ### end Alembic commands ###
