"""fix: evitando ciclos en relaciones

Revision ID: 7670f8d415e1
Revises: 1eec9bcd4a3c
Create Date: 2025-07-18 00:08:03.456845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7670f8d415e1'
down_revision: Union[str, None] = '1eec9bcd4a3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('target_images_exercise_id_fkey'), 'target_images', type_='foreignkey')
    op.drop_column('target_images', 'exercise_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('target_images', sa.Column('exercise_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('target_images_exercise_id_fkey'), 'target_images', 'practice_exercises', ['exercise_id'], ['id'])
    # ### end Alembic commands ###
