"""Valor por defecto al genero

Revision ID: 7687e4b16c5a
Revises: 585e90d35362
Create Date: 2025-07-14 04:44:39.126600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7687e4b16c5a'
down_revision: Union[str, None] = '585e90d35362'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
