"""Actualizando la base de datos

Revision ID: 88e6ed8f443a
Revises: 
Create Date: 2025-03-05 13:50:00.764448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88e6ed8f443a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shooting_clubs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('chief_instructor_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chief_instructor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chief_instructor_id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('shooters', sa.Column('club_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'shooters', 'shooting_clubs', ['club_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shooters', type_='foreignkey')
    op.drop_column('shooters', 'club_id')
    op.drop_table('shooting_clubs')
    # ### end Alembic commands ###
