"""agregando el campo de classification a el modelo de evaluacion

Revision ID: 954a4814da61
Revises: 34dc0c708091
Create Date: 2025-07-27 05:26:00.714018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '954a4814da61'
down_revision: Union[str, None] = '34dc0c708091'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
