"""Agregando la relacion de la session de practica individual

Revision ID: 9e12fc9b9230
Revises: 49b43e5a1a75
Create Date: 2025-04-13 13:24:29.719713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e12fc9b9230'
down_revision: Union[str, None] = '49b43e5a1a75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('individual_practice_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shooter_id', sa.UUID(), nullable=False),
    sa.Column('instructor_id', sa.UUID(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('total_shots_fired', sa.Integer(), nullable=True),
    sa.Column('total_hits', sa.Integer(), nullable=True),
    sa.Column('accuracy_percentage', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shooter_id'], ['shooters.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('individual_practice_sessions')
    # ### end Alembic commands ###
