"""Agregando datos adicionales a la informacion del usuario

Revision ID: adb5224154eb
Revises: 4888a1eb7247
Create Date: 2025-02-28 20:20:46.782436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adb5224154eb'
down_revision: Union[str, None] = '4888a1eb7247'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_biometric_data', sa.Column('time_sleep', sa.String(), nullable=True))
    op.add_column('user_biometric_data', sa.Column('blood_pressure', sa.String(), nullable=True))
    op.add_column('user_biometric_data', sa.Column('heart_rate', sa.String(), nullable=True))
    op.add_column('user_biometric_data', sa.Column('respiratory_rate', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_biometric_data', 'respiratory_rate')
    op.drop_column('user_biometric_data', 'heart_rate')
    op.drop_column('user_biometric_data', 'blood_pressure')
    op.drop_column('user_biometric_data', 'time_sleep')
    # ### end Alembic commands ###
