"""limpiando la evaluacion

Revision ID: b2c52305e39d
Revises: 677e4a438490
Create Date: 2025-07-22 06:16:16.935799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b2c52305e39d'
down_revision: Union[str, None] = '677e4a438490'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practice_evaluations', sa.Column('overall_technique_rating', sa.Float(), nullable=True))
    op.add_column('practice_evaluations', sa.Column('instructor_notes', sa.String(), nullable=True))
    op.drop_column('practice_evaluations', 'grip_rating')
    op.drop_column('practice_evaluations', 'classification')
    op.drop_column('practice_evaluations', 'trigger_control_rating')
    op.drop_column('practice_evaluations', 'posture_rating')
    op.drop_column('practice_evaluations', 'breathing_rating')
    op.drop_column('practice_evaluations', 'sight_alignment_rating')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practice_evaluations', sa.Column('sight_alignment_rating', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('practice_evaluations', sa.Column('breathing_rating', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('practice_evaluations', sa.Column('posture_rating', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('practice_evaluations', sa.Column('trigger_control_rating', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('practice_evaluations', sa.Column('classification', postgresql.ENUM('EXPERTO', 'CONFIABLE', 'MEDIO', 'REGULAR', name='shooterlevelenum'), autoincrement=False, nullable=False))
    op.add_column('practice_evaluations', sa.Column('grip_rating', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('practice_evaluations', 'instructor_notes')
    op.drop_column('practice_evaluations', 'overall_technique_rating')
    # ### end Alembic commands ###
