"""Agregando la relacion entre tipo de practica y ejercicio

Revision ID: c42a3753e4c6
Revises: 9e12fc9b9230
Create Date: 2025-04-13 14:40:56.127409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c42a3753e4c6'
down_revision: Union[str, None] = '9e12fc9b9230'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
