"""Actualizando la relacion weapon_ammunition_compatibility

Revision ID: e04fa48286a7
Revises: 556521ce90f0
Create Date: 2025-03-17 19:32:09.592983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e04fa48286a7'
down_revision: Union[str, None] = '556521ce90f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
