"""Nueva propuesta para almacenar los datos del analisis

Revision ID: ec29d19c718b
Revises: 7670f8d415e1
Create Date: 2025-07-18 06:02:49.900797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec29d19c718b'
down_revision: Union[str, None] = '7670f8d415e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('target_analyses', sa.Column('total_impacts_inside', sa.Integer(), nullable=True))
    op.add_column('target_analyses', sa.Column('total_impacts_outside', sa.Integer(), nullable=True))
    op.add_column('target_analyses', sa.Column('covered_impacts_inside', sa.Integer(), nullable=True))
    op.add_column('target_analyses', sa.Column('covered_impacts_outside', sa.Integer(), nullable=True))
    op.add_column('target_analyses', sa.Column('accuracy_percentage', sa.Float(), nullable=True))
    op.add_column('target_analyses', sa.Column('average_confidence', sa.Float(), nullable=True))
    op.add_column('target_analyses', sa.Column('confidence_stats', sa.JSON(), nullable=True))
    op.add_column('target_analyses', sa.Column('model_version', sa.String(), nullable=True))
    op.add_column('target_analyses', sa.Column('confidence_threshold', sa.Float(), nullable=True))
    op.drop_column('target_analyses', 'analysis_confidence')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('target_analyses', sa.Column('analysis_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('target_analyses', 'confidence_threshold')
    op.drop_column('target_analyses', 'model_version')
    op.drop_column('target_analyses', 'confidence_stats')
    op.drop_column('target_analyses', 'average_confidence')
    op.drop_column('target_analyses', 'accuracy_percentage')
    op.drop_column('target_analyses', 'covered_impacts_outside')
    op.drop_column('target_analyses', 'covered_impacts_inside')
    op.drop_column('target_analyses', 'total_impacts_outside')
    op.drop_column('target_analyses', 'total_impacts_inside')
    # ### end Alembic commands ###
