"""Actualizando el modelo de evaluacion

Revision ID: f41229210d09
Revises: b186523e1e25
Create Date: 2025-05-03 21:15:41.722381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f41229210d09'
down_revision: Union[str, None] = 'b186523e1e25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practice_evaluations', sa.Column('posture_rating', sa.Integer(), nullable=True))
    op.add_column('practice_evaluations', sa.Column('grip_rating', sa.Integer(), nullable=True))
    op.add_column('practice_evaluations', sa.Column('sight_alignment_rating', sa.Integer(), nullable=True))
    op.add_column('practice_evaluations', sa.Column('trigger_control_rating', sa.Integer(), nullable=True))
    op.add_column('practice_evaluations', sa.Column('breathing_rating', sa.Integer(), nullable=True))
    op.add_column('practice_evaluations', sa.Column('primary_issue_zone', sa.String(), nullable=True))
    op.add_column('practice_evaluations', sa.Column('secondary_issue_zone', sa.String(), nullable=True))
    op.add_column('practice_evaluations', sa.Column('avg_reaction_time', sa.Float(), nullable=True))
    op.add_column('practice_evaluations', sa.Column('avg_draw_time', sa.Float(), nullable=True))
    op.add_column('practice_evaluations', sa.Column('avg_reload_time', sa.Float(), nullable=True))
    op.add_column('practice_evaluations', sa.Column('hit_factor', sa.Float(), nullable=True))
    op.add_column('practice_evaluations', sa.Column('date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('practice_evaluations', 'date')
    op.drop_column('practice_evaluations', 'hit_factor')
    op.drop_column('practice_evaluations', 'avg_reload_time')
    op.drop_column('practice_evaluations', 'avg_draw_time')
    op.drop_column('practice_evaluations', 'avg_reaction_time')
    op.drop_column('practice_evaluations', 'secondary_issue_zone')
    op.drop_column('practice_evaluations', 'primary_issue_zone')
    op.drop_column('practice_evaluations', 'breathing_rating')
    op.drop_column('practice_evaluations', 'trigger_control_rating')
    op.drop_column('practice_evaluations', 'sight_alignment_rating')
    op.drop_column('practice_evaluations', 'grip_rating')
    op.drop_column('practice_evaluations', 'posture_rating')
    # ### end Alembic commands ###
